using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using ZBase.Utilities;

namespace ZBase.Classes
{
    [StructLayout(LayoutKind.Explicit)]
    public struct Nightmode
    {
        [FieldOffset(0x9D8)]
        public int bUseCustomAutoExposureMin;
        [FieldOffset(0x9D9)]
        public int bUseCustomAutoExposureMax;
        [FieldOffset(0x9DC)]
        public float m_flCustomAutoExposureMin;
        [FieldOffset(0x9E0)]
        public float m_flCustomAutoExposureMax;
    }
    [StructLayout(LayoutKind.Explicit)]
    public struct GlowStruct
    {
        [FieldOffset(0x00)]
        public int EntityPointer;
        [FieldOffset(0x4)]
        public float r;
        [FieldOffset(0x8)]
        public float g;
        [FieldOffset(0xC)]
        public float b;
        [FieldOffset(0x10)]
        public float a;
        [FieldOffset(0x14)]
        public int jnk1;
        [FieldOffset(0x18)]
        public int jnk2;
        [FieldOffset(0x1C)]
        public float BloomAmount;
        [FieldOffset(0x20)]
        public int jnk3;

        [FieldOffset(0x24)]
        public bool m_bRenderWhenOccluded;
        [FieldOffset(0x25)]
        public bool m_bRenderWhenUnoccluded;
        [FieldOffset(0x2C)]
        public int GlowStyle;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct player_info_s
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public char[] __pad0;
        public int m_nXuidLow;
        public int m_nXuidHigh;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public char[] m_szPlayerName;
        public int m_nUserID;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 33)]
        public char[] m_szSteamID;
        public uint m_nSteam3ID;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public char[] m_szFriendsName;
        [MarshalAs(UnmanagedType.U1, SizeConst = 1)]
        public bool m_bIsFakePlayer;
        [MarshalAs(UnmanagedType.U1, SizeConst = 1)]
        public bool m_bIsHLTV;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
        public int[] m_dwCustomFiles;
        public char m_FilesDownloaded;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct CharCodes
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 255)]
        public int[] tab;
    };

    public struct RECT
    {
        public int left, top, right, bottom;
    }

    public enum GameState
    {
        STATE_NONE = 0,
        CHALLENGE = 1,
        CONNECTED = 2,
        NEW = 3,
        PRESPAWN = 4,
        SPAWN = 5,
        FULL_CONNECTED = 6,
        CHANGELEVEL = 7
    }

    public enum Skins
    {
                MP7_Groundwater = 2,
                CandyApple = 3,
                ForestDDPAT = 5,
                ArcticCamo = 6,
                DesertStorm = 8,
                BengalTiger = 9,
                Copperhead = 10,
                Skulls = 11,
                CrimsonWeb = 12,
                BlueStreak = 13,
                RedLaminate = 14,
                Gunsmoke = 15,
                JungleTiger = 16,
                UranDDPAT = 17,
                Virus = 20,
                GraniteMarleized = 21,
                ContrastSpray = 22,
                ForestLeaves = 25,
                LichenDashed = 26,
                BoneMask = 27,
                AUG_AnodizedNavy = 28,
                SnakeCamo = 30,
                Silver = 32,
                MP9_HotRod = 33,
                MetallicDDPAT = 34,
                Ossified = 36,
                Blaze = 37,
                Fade = 38,
                Bulldozer = 39,
                Night = 40,
                Copper = 41,
                BlueSteel = 42,
                Stained = 43,
                CaseHardened = 44,
                Contractor = 46,
                Colony = 47,
                DragonTattoo = 48,
                LightningStrike = 51,
                Slaughter = 59,
                DarkWater = 60,
                Hypnotic = 61,
                Bloomstick = 62,
                ColdBlooded = 67,
                CaronFier = 70,
                Scorpion = 71,
                SafariMesh = 72,
                Wings = 73,
                PolarCamo = 74,
                BlizzardMarleized = 75,
                WinterForest = 76,
                BorealForest = 77,
                ForestNight = 78,
                OrangeDDPAT = 83,
                PinkDDPAT = 84,
                Mudder = 90,
                Cyanospatter = 92,
                Caramel = 93,
                Grassland = 95,
                BlueSpruce = 96,
                Ultraviolet = 98,
                GLOCK_SandDune = 99,
                Storm = 100,
                TEC9_Tornado = 101,
                Whiteout = 102,
                GrasslandLeaves = 104,
                PolarMesh = 107,
                Condemned = 110,
                GlacierMesh = 111,
                SandMesh = 116,
                SageSpray = 119,
                JungleSpray = 122,
                SandSpray = 124,
                UranPerforated = 135,
                WavesPerforated = 136,
                OrangePeel = 141,
                UranMasked = 143,
                JungleDashed = 147,
                SandDashed = 148,
                UranDashed = 149,
                XM_Jungle = 151,
                Demolition = 153,
                Afterimage = 154,
                BulletRain = 155,
                DeathyKitty = 156,
                SCAR20_Palm = 157,
                Walnut = 158,
                Brass = 159,
                Splash = 162,
                ModernHunter = 164,
                SplashJam = 165,
                BlazeOrange = 166,
                M4A4_RadiationHazard = 167,
                TEC9_NuclearThreat = 168,
                P90_FalloutWarning = 169,
                Predator = 170,
                IrradiatedAlert = 171,
                BlackLaminate = 172,
                BOOM = 174,
                Scorched = 175,
                FadedZera = 176,
                Memento = 177,
                Doomkitty = 178,
                TEC9_NuclearThreat_2 = 179,
                FireSerpent = 180,
                AWP_Corticera = 181,
                EmeraldDragon = 182,
                Overgrowth = 183,
                P2000_Corticera = 184,
                GoldenKoi = 185,
                WaveSpray = 186,
                Zirka = 187,
                Graven = 188,
                M4A1S_BrightWater = 189,
                BlackLima = 190,
                Tempest = 191,
                Shattered = 192,
                BonePile = 193,
                Spitfire = 194,
                Demeter = 195,
                SCAR20_Emerald = 196,
                AUG_AnodizedNavy_2 = 197,
                Hazard = 198,
                DrySeason = 199,
                MayanDreams = 200,
                NEGEV_Palm = 201,
                JungleDDPAT = 202,
                RustCoat = 203,
                Mosaico = 204,
                XM_Jungle_2 = 205,
                TEC9_Tornado_2 = 206,
                Facets = 207,
                GLOCK_SandDune_2 = 208,
                MP7_Groundwater_2 = 209,
                AnodizedGunmetal = 210,
                P2000_OceanFoam = 211,
                AWP_Graphite = 212,
                P2000_OceanFoam_2 = 213,
                NOVA_Graphite = 214,
                X_Ray = 215,
                BlueTitanium = 216,
                BloodTiger = 217,
                Hexane = 218,
                Hive = 219,
                Hemogloin = 220,
                Serum = 221,
                BloodintheWater = 222,
                Nightshade = 223,
                WaterSigil = 224,
                GhostCamo = 225,
                BlueLaminate = 226,
                ElectricHive = 227,
                BlindSpot = 228,
                AzureZera = 229,
                SteelDisruption = 230,
                CoaltDisruption = 231,
                SCAR20_CrimsonWeb = 232,
                TropicalStorm = 233,
                AshWood = 234,
                VariCamo = 235,
                NightOps = 236,
                UranRule = 237,
                VariCamoBlue = 238,
                CaliCamo = 240,
                HuntingBlind = 241,
                ArmyMesh = 242,
                GatorMesh = 243,
                Teardown = 244,
                ArmyRecon = 245,
                P2000_AmberFade = 246,
                SG553_DamascusSteel = 247,
                RedQuartz = 248,
                CoaltQuartz = 249,
                FullStop = 250,
                PitViper = 251,
                SilverQuartz = 252,
                AcidFade = 253,
                CZ75A_Nitro = 254,
                M4A4_Asiimov = 255,
                TheKraken = 256,
                M4A1S_Guardian = 257,
                Mehndi = 258,
                AWP_Redline = 259,
                FAMAS_Pulse = 260,
                Marina = 261,
                RoseIron = 262,
                RisingSkull = 263,
                GALILAR_Sandstorm = 264,
                FIVESEVEN_Kami = 265,
                Magma = 266,
                CoaltHalftone = 267,
                TreadPlate = 268,
                TheFuschiaIsNow = 269,
                Victoria = 270,
                Undertow = 271,
                TitaniumBit = 272,
                Heirloom = 273,
                CopperGalaxy = 274,
                RedFragCam = 275,
                Panther = 276,
                Stainless = 277,
                BlueFissure = 278,
                AWP_Asiimov = 279,
                Chameleon = 280,
                Corporal = 281,
                AK47_Redline = 282,
                Trigon = 283,
                MAC10_Heat = 284,
                Terrain = 285,
                NOVA_Antique = 286,
                SG553_Pulse = 287,
                Sergeant = 288,
                TEC9_Sandstorm = 289,
                USPS_Guardian = 290,
                MAG7_HeavenGuard = 291,
                DeathRattle = 293,
                GreenApple = 294,
                Franklin = 295,
                Meteorite = 296,
                Tuxedo = 297,
                ArmySheen = 298,
                CagedSteel = 299,
                EmeraldPinstripe = 300,
                AtomicAlloy = 301,
                Vulcan = 302,
                Isaac = 303,
                Slashed = 304,
                AUG_Torque = 305,
                PPBIZON_Antique = 306,
                Retriution = 307,
                GalilAR_Kami = 308,
                Howl = 309,
                Curse = 310,
                DesertWarfare = 311,
                SCAR20_Cyrex = 312,
                Orion = 313,
                XM1014_HeavenGuard = 314,
                PoisonDart = 315,
                Jaguar = 316,
                Bratatat = 317,
                RoadRash = 318,
                Detour = 319,
                RedPython = 320,
                MasterPiece = 321,
                CZ75A_Nitro_2 = 322,
                RustCoat_2 = 323,
                Chalice = 325,
                Knight = 326,
                Chainmail = 327,
                HandCannon = 328,
                DarkAge = 329,
                Briar = 330,
                RoyalBlue = 332,
                Indigo = 333,
                Twist = 334,
                Module = 335,
                M4A4_Desert_Strike = 336,
                Tatter = 337,
                Pulse = 338,
                Caiman = 339,
                JetSet = 340,
                AK47_FirstClass = 341,
                Leather = 342,
                Commuter = 343,
                DragonLore = 344,
                SAWEDOFF_FirstClass = 345,
                CoachClass = 346,
                Pilot = 347,
                RedLeather = 348,
                Osiris = 349,
                Tigris = 350,
                Conspiracy = 351,
                FowlPlay = 352,
                WaterElemental = 353,
                UranHazard = 354,
                NEGEV_Desert_Strike = 355,
                Koi = 356,
                Ivory = 357,
                Supernova = 358,
                P90_Asiimov = 359,
                M4A1S_Cyrex = 360,
                Ayss = 361,
                Layrinth = 362,
                Traveler = 363,
                BusinessClass = 364,
                OlivePlaid = 365,
                GreenPlaid = 366,
                Reactor = 367,
                SettingSun = 368,
                NuclearWaste = 369,
                BoneMachine = 370,
                Styx = 371,
                NuclearGarden = 372,
                Contamination = 373,
                Toxic = 374,
                AUG_RadiationHazard = 375,
                ChemicalGreen = 376,
                HotShot = 377,
                SG553_FalloutWarning = 378,
                Cererus = 379,
                AK47_WastelandRebel = 380,
                Grinder = 381,
                Murky = 382,
                Basilisk = 383,
                Griffin = 384,
                Firestarter = 385,
                Dart = 386,
                UrbanHazard = 387,
                P250_Cartel = 388,
                FireElemental = 389,
                Highwayman = 390,
                Cardiac = 391,
                Delusion = 392,
                Tranquility = 393,
                AK47_Cartel = 394,
                AWP_Manowar = 395,
                UranShock = 396,
                Naga = 397,
                Chatterox = 398,
                Catacoms = 399,
                DragonKing = 400,
                SystemLock = 401,
                Malachite = 402,
                DeadlyPoison = 403,
                Muertos = 404,
                Serenity = 405,
                Grotto = 406,
                Quicksilver = 407,
                TigerTooth = 409,
                DamascusSteel_DARK = 411,
                DamascusSteel_BRIGHT = 410,
                Marble_Fade = 413,
                RustCoat_3 = 414,
                Doppler_RUBY = 415,
                Doppler_SAPPHIRE = 416,
                Doppler_BLACKPEARL = 417,
                Doppler_PHASE1 = 418,
                Doppler_PHASE2 = 419,
                Doppler_PHASE3 = 420,
                Doppler_PHASE4 = 421,
                AK47_EliteBuild = 422,
                ArmorCore = 423,
                WormGod = 424,
                BronzeDeco = 425,
                P250_Valence = 426,
                MonkeyBusiness = 427,
                Eco = 428,
                Djinn = 429,
                M4A1S_HyperBeast = 430,
                MAG7_Heat = 431,
                NEGEV_Manowar = 432,
                NeonRider = 433,
                Origami = 434,
                PolePosition = 435,
                GrandPrix = 436,
                TwilightGalaxy = 437,
                Chronos = 438,
                Hades = 439,
                IcarusFell = 440,
                MinotaursLabyrinth = 441,
                Asterion = 442,
                Pathfinder = 443,
                Daedalus = 444,
                M4A1S_HotRod = 445,
                Medusa = 446,
                Duelist = 447,
                MP9_PandorasBox = 448,
                Poseidon = 449,
                MooninLira = 450,
                SuninLeo = 451,
                ShippingForecast = 452,
                CZ7A_Emerald = 453,
                ParaGreen = 454,
                AkihabaraAccept = 455,
                Hydroponic = 456,
                BamooPrint = 457,
                BamooShadow = 458,
                BamooForest = 459,
                AquaTerrace = 460,
                CounterTerrace = 462,
                Terrace = 463,
                NeonKimono = 464,
                OrangeKimono = 465,
                CrimsonKimono = 466,
                MintKimono = 467,
                MidnightStorm = 468,
                SunsetStorm = 469,
                SunsetStorm_2 = 470,
                Dayreak = 471,
                ImpactDrill = 472,
                Seaird = 473,
                AquamarineRevenge = 474,
                AWP_HyperBeast = 475,
                YellowJacket = 476,
                NeuralNet = 477,
                RocketPop = 478,
                BunsenBurner = 479,
                EvilDaimyo = 480,
                Nemesis = 481,
                RuyPoisonDart = 482,
                Loudmouth = 483,
                Ranger = 484,
                Handgun = 485,
                P90_EliteBuild = 486,
                SG553_Cyrex = 487,
                Riot = 488,
                USPS_Torque = 489,
                FrontsideMisty = 490,
                DualingDragons = 491,
                SurvivorZ = 492,
                Flux = 493,
                StoneCold = 494,
                Wraiths = 495,
                NeulaCrusader = 496,
                GoldenCoil = 497,
                Rangeen = 498,
                CoaltCore = 499,
                SpecialDelivery = 500,
                Wingshot = 501,
                GreenMarine = 502,
                BigIron = 503,
                KillConfirmed = 504,
                XM1014_Scumria = 505,
                PointDisarray = 506,
                Ricochet = 507,
                FuelRod = 508,
                Corinthian = 509,
                Retroution = 510,
                TheExecutioner = 511,
                RoyalPaladin = 512,
                PowerLoader = 514,
                Imperial = 515,
                Shapewood = 516,
                Yorick = 517,
                Outreak = 518,
                TigerMoth = 519,
                Avalanche = 520,
                TecluBurner = 521,
                R8_Fade = 522,
                R8_AmberFade = 523,
                AK47_FuelInjector = 524,
                EliteBuild = 525,
                PhoticZone = 526,
                KumichoDragon = 527,
                Cartel = 528,
                FAMAS_Valence = 529,
                Triumvirate = 530,
                RoyalLegion = 532,
                TheBattlestar = 533,
                LapisGator = 534,
                Praetorian = 535,
                Impire = 536,
                NOVA_HyperBeast = 537,
                Necropos = 538,
                Jamiya = 539,
                LeadConduit = 540,
                Doppler_1 = 617,
                Doppler_2 = 618,
                Doppler_3 = 619,
                Ultraviolet_1 = 620,
                Ultraviolet_2 = 621,
                FleetFlock = 541,
                JudgementofAnuis = 542,
                RedAstor = 543,
                Ventilators = 544,
                OrangeCrash = 545,
                Firefight = 546,
                Spectre = 547,
                Chanticos_Fire = 548,
                Bioleak = 549,
                Oceanic = 550,
                P250_Asiimov = 551,
                Fuar = 552,
                Atlas = 553,
                GhostCrusader = 554,
                Re_Entry = 555,
                PrimalSaer = 556,
                BlackTie = 557,
                Lore_BAYONET = 558,
                Lore_FLIP = 559,
                Lore_GUT = 560,
                Lore_KARAMBIT = 561,
                Lore_M9BAYONET = 562,
                BlackLaminate_BAYONET = 563,
                BlackLaminate_FLIP = 564,
                BlackLaminate_GUT = 565,
                BlackLaminate_KARAMBIT = 566,
                BlackLaminate_M9BAYONET = 567,
                GammaDoppler_EMERALD = 568,
                GammaDoppler_PHASE1 = 569,
                GammaDoppler_PHASE2 = 570,
                GammaDoppler_PHASE3 = 571,
                GammaDoppler_PHASE4 = 572,
                Autotronic_BAYONET = 573,
                Autotronic_FLIP = 574,
                Autotronic_GUT = 575,
                Autotronic_KARAMBIT = 576,
                Autotronic_M9BAYONET = 577,
                BrightWater = 578,
                BrightWater_M9BAYONET = 579,
                Freehand = 580,
                Freehand_M9BAYONET = 581,
                Freehand_KARAMBIT = 582,
                Aristocrat = 583,
                Phoos = 584,
                ViolentDaimyo = 585,
                GLOCK_WastelandRebel = 586,
                M4A1S_MechaIndustries = 587,
                DESERT_EAGLE_MechaIndustries = 805,
                DesolateSpace = 588,
                Carnivore = 589,
                Exo = 590,
                ImperialDragon = 591,
                IronClad = 592,
                Chopper = 593,
                Harvester = 594,
                Reoot = 595,
                Limelight = 596,
                SCAR20_Bloodsport = 597,
                Aerial = 598,
                IceCap = 599,
                NeonRevolution = 600,
                SydMead = 601,
                Imprint = 602,
                Directive = 603,
                RollCage = 604,
                FIVESEVEN_Scumria = 605,
                Ventilator = 606,
                Weasel = 607,
                Petroglyph = 608,
                Airlock = 609,
                Dazzle = 610,
                Grim = 611,
                Powercore = 612,
                Triarch = 613,
                TEC9_FuelInjector = 614,
                Briefing = 615,
                Slipstream = 616,
                Polymer = 622,
                Ironwork = 623,
                Dragonfire = 624,
                RoyalConsorts = 625,
                FAMAS_MechaIndustries = 626,
                Cirrus = 627,
                Stinger = 628,
                BlackSand = 629,
                SandScale = 630,
                Flashack = 631,
                BuzzKill = 632,
                Sonar = 633,
                Gila = 634,
                Turf = 635,
                ShallowGrave = 636,
                USPS_Cyrex = 637,
                WastelandPrincess = 638,
                AK47_Bloodsport = 639,
                FeverDream = 640,
                JungleSlipstream = 641,
                SCAR20_Blueprint = 642,
                Xiangliu = 643,
                Decimator = 644,
                OxideBlaze = 645,
                Capillary = 646,
                CrimsonTsunami = 647,
                EmeraldPoisonDart = 648,
                Akoen = 649,
                Ripple = 650,
                LastDive = 651,
                Scaffold = 652,
                USPS_Neo_Noir = 653,
                Seasons = 654,
                Zander = 655,
                OritMk01 = 656,
                USPS_Blueprint = 657,
                CoraStrike = 658,
                Macare = 659,
                FIVESEVEN_HyperBeast = 660,
                SugarRush = 661,
                OniTaiji = 662,
                Briefing_2 = 663,
                Hellfire = 664,
                Aloha = 665,
                HardWater = 666,
                Woodsman = 667,
                RedRock = 668,
                DeathGrip = 669,
                sHead = 670,
                CutOut = 671,
                MetalFlowers = 672,
                Morris = 673,
                Triqua = 674,
                TheEmpress = 675,
                HighRoller = 676,
                Hunter = 677,
                SeeYaLater = 678,
                Goo = 679,
                OffWorld = 680,
                LeadedGlass = 681,
                Oceanic_2 = 682,
                LlamaCannon = 683,
                CrackedOpal = 684,
                JungleSlipstream_2 = 685,
                Phantom = 686,
                Tacticat = 687,
                Exposure = 688,
                Ziggy = 689,
                Stymphalian = 690,
                Mortis = 691,
                NightRiot = 692,
                FlameTest = 693,
                Moonrise = 694,
                M4A1S_Neo_Noir = 695,
                MP7_Bloodsport = 696,
                BlackSand_2 = 697,
                Lionfish = 698,
                WildSix = 699,
                UranHazard_2 = 700,
                Grip = 701,
                Aloha_2 = 702,
                SWAG_7 = 703,
                ArcticWolf = 704,
                Cortex = 705,
                OxideBlaze_2 = 706
}

public enum Ranks
    {
        Unranked = 0,
        SilverI = 1,
        SilverII = 2,
        SilverIII = 3,
         SilverIV  = 4,
         SilverElite  = 5 ,
         SilverEliteMaster  =    6  ,   
         GoldNovaI  =7,
         GoldNovaII  =8,
         GoldNovaIII  =9,
         GoldNovaMaster  =10,
         MasterGuardianI  = 11,
         MasterGuardianII   = 12,
         MasterGuardianElite  =13,
         DistinguishedMasterGuardian  = 14,
         LegendaryEagle  = 15,
         LegendaryEagleMaster  = 16,
         SupremeMasterFirstClass  =17,
         TheGlobalElite = 18,
    }

    public enum WeaponsID
    {
        DEAGLE = 1,
        BERETTAS = 2,
        FIVESEVEN = 3,
        GLOCK = 4,
        AK47 = 7,
        AUG = 8,
        AWP = 9,
        FAMAS = 10,
        G3SG1 = 11,
        GALILAR = 13,
        M249 = 14,
        M4A4 = 16,
        MAC10 = 17,
        P90 = 19,
        MP5SD = 23,
        MP5SDOnline = 262167,
        MP5SDOnline2 = 196631,
        UMP45 = 24,
        XM1014 = 25,
        BIZON = 26,
        MAG7 = 27,
        NEGEV = 28,
        SAWEDOFF = 29,
        TEC9 = 30,
        TASER = 31,
        TASEROnline = 196639,
        P2000 = 32,
        MP7 = 33,
        MP9 = 34,
        NOVA = 35,
        P250 = 36,
        SCAR20 = 38,
        SG556 = 39,
        SSG08 = 40,
        KNIFE = 42,
        KNIFE_T = 59,
        FLASHBANG = 43,
        HEGRENADE = 44,
        SMOKEGRENADE = 45,
        MOLOTOV = 46,
        DECOY = 47,
        INCGRENADE = 48,
        C4 = 49,
        M4A1S = 60,
        WEAPON_KNIFE_GG = 41,
        WEAPON_BAYONET = 500,
        WEAPON_FLIP_KNIFE = 505,
        WEAPON_GUT_KNIFE = 506,
        WEAPON_KARAMBIT = 507,
        WEAPON_M9_BAYONET = 508,
        WEAPON_HUNTSMAN_KNIFE = 509,
        WEAPON_FALCHION_KNIFE = 512,
        WEAPON_BOWIE_KNIFE = 514,
        WEAPON_BUTTERFLY_KNIFE = 515,
        WEAPON_SHADOW_DAGGERS = 516,
        WEAPON_URSUS_KNIFE = 519,
        WEAPON_NAVAJA_KNIFE = 520,
        WEAPON_STILETTO_KNIFE = 522,
        WEAPON_TALON_KNIFE = 523,
        M4A1SOnline = 262204,
        M4A1SOnline2 = 196668,
        USPS = 61,
        USPSOnline = 262205,
        USPSOnline2 = 196669,
        CZ75A = 63,
        CZ75AOnline = 262207,
        CZ75AOnline2 = 196671,
        REVOLVER = 64,
        REVOLVEROnline = 262208,
        REVOLVEROnline2 = 196672,
    }

    public enum CLASSID
    {
        CAI_BaseNPC = 0,
        CAK47,
        CBaseAnimating,
        CBaseAnimatingOverlay,
        CBaseAttributableItem,
        CBaseButton,
        CBaseCombatCharacter,
        CBaseCombatWeapon,
        CBaseCSGrenade,
        CBaseCSGrenadeProjectile,
        CBaseDoor,
        CBaseEntity,
        CBaseFlex,
        CBaseGrenade,
        CBaseParticleEntity,
        CBasePlayer,
        CBasePropDoor,
        CBaseTeamObjectiveResource,
        CBaseTempEntity,
        CBaseToggle,
        CBaseTrigger,
        CBaseViewModel,
        CBaseVPhysicsTrigger,
        CBaseWeaponWorldModel,
        CBeam,
        CBeamSpotlight,
        CBoneFollower,
        CBRC4Target,
        CBreachCharge,
        CBreachChargeProjectile,
        CBreakableProp,
        CBreakableSurface,
        CC4,
        CCascadeLight,
        CChicken,
        CColorCorrection,
        CColorCorrectionVolume,
        CCSGameRulesProxy,
        CCSPlayer,
        CCSPlayerResource,
        CCSRagdoll,
        CCSTeam,
        CDangerZone,
        CDangerZoneController,
        CDEagle,
        CDecoyGrenade,
        CDecoyProjectile,
        CDrone,
        CDronegun,
        CDynamicLight,
        CDynamicProp,
        CEconEntity,
        CEconWearable,
        CEmbers,
        CEntityDissolve,
        CEntityFlame,
        CEntityFreezing,
        CEntityParticleTrail,
        CEnvAmbientLight,
        CEnvDetailController,
        CEnvDOFController,
        CEnvGasCanister,
        CEnvParticleScript,
        CEnvProjectedTexture,
        CEnvQuadraticBeam,
        CEnvScreenEffect,
        CEnvScreenOverlay,
        CEnvTonemapController,
        CEnvWind,
        CFEPlayerDecal,
        CFireCrackerBlast,
        CFireSmoke,
        CFireTrail,
        CFish,
        CFists,
        CFlashbang,
        CFogController,
        CFootstepControl,
        CFunc_Dust,
        CFunc_LOD,
        CFuncAreaPortalWindow,
        CFuncBrush,
        CFuncConveyor,
        CFuncLadder,
        CFuncMonitor,
        CFuncMoveLinear,
        CFuncOccluder,
        CFuncReflectiveGlass,
        CFuncRotating,
        CFuncSmokeVolume,
        CFuncTrackTrain,
        CGameRulesProxy,
        CGrassBurn,
        CHandleTest,
        CHEGrenade,
        CHostage,
        CHostageCarriableProp,
        CIncendiaryGrenade,
        CInferno,
        CInfoLadderDismount,
        CInfoMapRegion,
        CInfoOverlayAccessor,
        CItem_Healthshot,
        CItemCash,
        CItemDogtags,
        CKnife,
        CKnifeGG,
        CLightGlow,
        CMaterialModifyControl,
        CMelee,
        CMolotovGrenade,
        CMolotovProjectile,
        CMovieDisplay,
        CParadropChopper,
        CParticleFire,
        CParticlePerformanceMonitor,
        CParticleSystem,
        CPhysBox,
        CPhysBoxMultiplayer,
        CPhysicsProp,
        CPhysicsPropMultiplayer,
        CPhysMagnet,
        CPhysPropAmmoBox,
        CPhysPropLootCrate,
        CPhysPropRadarJammer,
        CPhysPropWeaponUpgrade,
        CPlantedC4,
        CPlasma,
        CPlayerResource,
        CPointCamera,
        CPointCommentaryNode,
        CPointWorldText,
        CPoseController,
        CPostProcessController,
        CPrecipitation,
        CPrecipitationBlocker,
        CPredictedViewModel,
        CProp_Hallucination,
        CPropCounter,
        CPropDoorRotating,
        CPropJeep,
        CPropVehicleDriveable,
        CRagdollManager,
        CRagdollProp,
        CRagdollPropAttached,
        CRopeKeyframe,
        CSCAR17,
        CSceneEntity,
        CSensorGrenade,
        CSensorGrenadeProjectile,
        CShadowControl,
        CSlideshowDisplay,
        CSmokeGrenade,
        CSmokeGrenadeProjectile,
        CSmokeStack,
        CSpatialEntity,
        CSpotlightEnd,
        CSprite,
        CSpriteOriented,
        CSpriteTrail,
        CStatueProp,
        CSteamJet,
        CSun,
        CSunlightShadowControl,
        CSurvivalSpawnChopper,
        CTablet,
        CTeam,
        CTeamplayRoundBasedRulesProxy,
        CTEArmorRicochet,
        CTEBaseBeam,
        CTEBeamEntPoint,
        CTEBeamEnts,
        CTEBeamFollow,
        CTEBeamLaser,
        CTEBeamPoints,
        CTEBeamRing,
        CTEBeamRingPoint,
        CTEBeamSpline,
        CTEBloodSprite,
        CTEBloodStream,
        CTEBreakModel,
        CTEBSPDecal,
        CTEBubbles,
        CTEBubbleTrail,
        CTEClientProjectile,
        CTEDecal,
        CTEDust,
        CTEDynamicLight,
        CTEEffectDispatch,
        CTEEnergySplash,
        CTEExplosion,
        CTEFireBullets,
        CTEFizz,
        CTEFootprintDecal,
        CTEFoundryHelpers,
        CTEGaussExplosion,
        CTEGlowSprite,
        CTEImpact,
        CTEKillPlayerAttachments,
        CTELargeFunnel,
        CTEMetalSparks,
        CTEMuzzleFlash,
        CTEParticleSystem,
        CTEPhysicsProp,
        CTEPlantBomb,
        CTEPlayerAnimEvent,
        CTEPlayerDecal,
        CTEProjectedDecal,
        CTERadioIcon,
        CTEShatterSurface,
        CTEShowLine,
        CTesla,
        CTESmoke,
        CTESparks,
        CTESprite,
        CTESpriteSpray,
        CTest_ProxyToggle_Networkable,
        CTestTraceline,
        CTEWorldDecal,
        CTriggerPlayerMovement,
        CTriggerSoundOperator,
        CVGuiScreen,
        CVoteController,
        CWaterBullet,
        CWaterLODControl,
        CWeaponAug,
        CWeaponAWP,
        CWeaponBaseItem,
        CWeaponBizon,
        CWeaponCSBase,
        CWeaponCSBaseGun,
        CWeaponCycler,
        CWeaponElite,
        CWeaponFamas,
        CWeaponFiveSeven,
        CWeaponG3SG1,
        CWeaponGalil,
        CWeaponGalilAR,
        CWeaponGlock,
        CWeaponHKP2000,
        CWeaponM249,
        CWeaponM3,
        CWeaponM4A1,
        CWeaponMAC10,
        CWeaponMag7,
        CWeaponMP5Navy,
        CWeaponMP7,
        CWeaponMP9,
        CWeaponNegev,
        CWeaponNOVA,
        CWeaponP228,
        CWeaponP250,
        CWeaponP90,
        CWeaponSawedoff,
        CWeaponSCAR20,
        CWeaponScout,
        CWeaponSG550,
        CWeaponSG552,
        CWeaponSG556,
        CWeaponSSG08,
        CWeaponTaser,
        CWeaponTec9,
        CWeaponTMP,
        CWeaponUMP45,
        CWeaponUSP,
        CWeaponXM1014,
        CWorld,
        CWorldVguiText,
        DustTrail,
        MovieExplosion,
        ParticleSmokeGrenade,
        RocketTrail,
        SmokeTrail,
        SporeExplosion,
        SporeTrail,
    }
}
